[character]
error_symbol = "[âœ—](bold red) "

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "

[[battery.display]]
threshhold = 10
style = "bold red"

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

